name: testing-app
on: [push]
jobs:
  run-tests-app:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run test:unit
